### ISSUE TITLE
Do bot still work?

### ISSUE THREAD

**Issue by royruzaini** [chief-gant/SplinterlandsTraderBot#10]
I having this not sure if it working or not
Error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Lost connection or internal error on node: https://rpc.ecency.com (1/100)

**Comment by chief-gant** [comment]
Hey! The bot is working.

The error you're getting seems to be API related. Do you have any other scripts that use the API running at the same time?

I would suggest waiting for a while (15min - 1hr) and then tryying again.

If it gives you an error again, please copy paste as much as you can see in the window, so I know exactly at what point you're getting the error.

**Comment by chief-gant** [comment]
This error you're getting happens every now and then, but you shouldn't mind it, unless it happens constantly. In my case, for example, what I see is:

```
Checking latest blocks...

Updating our posts


Checking latest blocks...
Error: Bad Gateway
Retry RPC Call on node: https://rpc.ecency.com (1/5) 

Retrying in 0 seconds


Updating our posts


Checking latest blocks...

Updating our posts
```

It gives a temporary error during the execution but it fixes itself by retrying in X seconds (in my case, 0). Then you can see it keeps working as usual.

**Comment by chief-gant** [comment]
I will close this issue as there doesn't seem to be anything to fix.

**Comment by ralts00** [comment]
@chief-gant Do bot still work? with new cards?
