### ISSUE TITLE
Splinterlands API Seems Down

### ISSUE THREAD

**Issue by knightblaster** [chief-gant/SplinterlandsTraderBot#2]
Getting a lot of "The Splinterlands API seems to be down or non-responding. We have to wait until its back up." Not sure if it is an issue or not, but saw this issue when it was trying to calculate the sale price of a card that got sold recently. Not sure if there is anything that can be done on your end, but just thought I would report the issue anyways. Been like this for about an hour and a half so far.

**Comment by knightblaster** [comment]
If you are using https://api.splinterlands.io/ I would suggest either switching to https://api2.splinterlands.com/ or using one as a primary, and the other as a secondary in case the first one goes down :) And, there is actually a third API link here, in case you want to add double redundancy: http://api.splinterlands.com/

**Comment by Macpayne** [comment]
Same issue start bot up, 1st iteration -- 

Starting iteration
Parameters:{'check_interval': 0, 'fixed_price_interval': 300, 'minimum_balance': 0, 'min_abs_gain': 0.1, 'min_rel_gain': 0.1, 'min_post_number': 50}
Balance: $6.83

No good offers found

We match the lowest price of: Goblin Firemage
We match the lowest price of: Charlok Minotaur
We match the lowest price of: Hill Giant
We match the lowest price of: Venari Crystalsmith
We match the lowest price of: Boogeyman
Card found, it has the lowest price: Flame Monkey
We match the lowest price of: Pelacor Conjurer
We match the lowest price of: Acid Shooter
Card updating: Biceratops
Card updating: Wave Runner
We match the lowest price of: Venari Wavesmith
We match the lowest price of: Shadow Snitch
We match the lowest price of: Blinding Reflector
We match the lowest price of: Merdaali Guardian
We match the lowest price of: Fineas Rage
We match the lowest price of: Centauri Mage
We match the lowest price of: Phantasm
Card sold: Life Sapper
Looking for the sale price of Life Sapper
The Splinterlands API seems to be down or non-responding. We have to wait until its back up.

Card sold last night, have tried to run bot 3 separate times same message just sits there for hours, where before it would go to another iteration.  Cant wait to get back to flipping cards, looking forward to your fix.

**Comment by royruzaini** [comment]
Same problem here, do this will fix after we wait?

**Comment by knightblaster** [comment]
It was down for about 20 hours yesterday, and then up for about 8 hours, and then down again. I highly suggest migrating to the api2 one... for example, the first 2 links will not work right now, but the last one does:

https://api.splinterlands.io/market/history?player=aktdo
http://api.splinterlands.com/market/history?player=aktdo
https://api2.splinterlands.com/market/history?player=aktdo

Also, the api2 one seems to always be a lot faster than the other two :)

**Comment by FranSollima** [comment]
I'm sorry for the delayed answer! I'll be checking out how the three fare against each other (api2.splinterlands.com seems the best one) and I'll use it as the main API. I'll also add the other 2 as backup.

**Comment by chief-gant** [comment]
I'm sorry for the delayed answer! I'll be checking out how the three fare against each other (api2.splinterlands.com seems the best one) and I'll use it as the main API. I'll also add the other 2 as backup.

**Comment by chief-gant** [comment]
I just made the corrections, so feel free to push the latest version. It should be somewhat faster and the API not responding error should be less likely to occur. I'll wait a few days before closing the issue.

**Comment by knightblaster** [comment]
No worries at all! Thanks for the update! :)
