### ISSUE TITLE
How do I know that you will not steal my keys?

### ISSUE THREAD

**Issue by silmono-cloud** [chief-gant/SplinterlandsTraderBot#4]
It's shady if anyone downloading,
**[Tell me bro how many keys have you stolen]**

**Comment by chief-gant** [comment]
You can't know for sure. I can assure you I won't, but it's up to you to believe me.

I should mention that the bot currently has a lot of users, and this repo has 5 stars and 22 unique cloners as of today.

But in the end, it's your call.

**Comment by knightblaster** [comment]
You do not, but as he said, a lot of us are using this... I have been using it for a little less than a month now, And my account is still mine.
